version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    image: rovingeye/logstash:6.5.1
    volumes:
      - ./logstash/config/:/usr/share/logstash/config/:ro
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    command: --config.reload.automatic
    networks:
      - elk
    depends_on:
#      - kafka
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

#  zookeeper:
#    image: zookeeper:3.4.11
#    ports:
#      - "2181:2181"
#    networks:
#      - elk
#
#  kafka:
#    build:
#      context: kafka/
#    image: rovingeye/kafka:1.1.0
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_CREATE_TOPICS: "BAM_LOG:1:1, BAD_LOG:1:1"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - elk
#    depends_on:
#      - zookeeper

networks:
  elk:
    driver: bridge
